config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # route 'static_pages#landing'
  root to: 'static_pages#landing'
  resources :users, except: [:destroy]
  resource :sessions, only: [:create, :new, :destroy]
  resources :dashboard, only: [:index]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :posts, only: [:new, :show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate!
    unless current_user
      redirect_to root_path
      flash[:danger] = "You need to login first"
    end
  end

  def current_user
    return unless cookies.signed[:id]
    @current_user ||= User.find_by(id: cookies.signed[:id])
  end
  helper_method :current_user    
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate!

  def index
    @hello_message = "Hipstergram welcomes you!"
    @posts = current_user.posts
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(reset_password_params)

    if user
      user.update(password_reset_token: password_reset_token, password_reset_at: DateTime.now)
      PasswordResetsMailer.password_reset_mail(user).deliver_now
      flash[:success] = "We've sent you instructions on how to reset your password"
    else
      flash[:danger] = "User does not exist"
    end

    redirect_to new_password_reset_path
  end

  def edit
    @token = params[:id]
  end

  def update
    @user = User.find_by(password_reset_token: params[:id])

    if @user && token_active?
      @user.update(password: user_params[:password], password_reset_token: nil, password_reset_at: nil)
      flash[:success] = "Password updated, you may log in now"
      redirect_to root_path
    else
      flash[:danger] = "Error, token is invalid or had expired"
      redirect_to edit_password_reset_path(id: params[:id])
    end
  end

  private

  def reset_password_params
    params.require(:reset).permit(:email)
  end

  def user_params
    params.require(:user).permit(:password)
  end

  def password_reset_token
    SecureRandom.urlsafe_base64
  end

  def token_active?
    (Time.now - @user.password_reset_at) < 24.hours
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def create
    @post = current_user.posts.create(post_params)

    if @post.persisted?
      redirect_to post_path(@post)
      flash[:success] = "New post created"
    else
      render :new
      flash[:danger] = "Error creating post"
    end
  end

private

def post_params
  params.require(:post).permit(:image, :caption)
end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate!, only: [:destroy]

  def new
  end

  def create
    user = User.find_by(email: user_params[:email])
               &.authenticate(user_params[:password])

    if user
      cookies.permanent.signed[:id] = user.id
      flash[:success] = "Welcome back #{current_user.username}"
      redirect_to root_path
    else
      flash[:danger] = "Error logging in"
      redirect_to new_sessions_path
    end

  end

  def destroy
    cookies.delete(:id)
    flash[:success] = "You've been logged out"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def landing
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.create(user_params)

    if @user.persisted?
      cookies.permanent.signed[:id] = @user.id
      flash[:success] = "You've registered"
      redirect_to root_path
    else
      flash[:danger] = @user.errors.full_messages
      redirect_to new_user_path
    end

  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_messages_helper.rb
module FlashMessagesHelper

  def display_message(value)

    return content_tag(:p, value) unless value.kind_of?(Array)

    content_tag :ul do
      value.collect { |message| content_tag(:li, message, class: 'list-styling')}.join.html_safe
    end
  end
end    

app/views/dashboard/index.html.erb
<html>
  <body>
    <section class="dashboard">

      <row>
        <div class="content">
          <h2 class="text"><%= "Hello #{current_user.username}" %></h2>
          <h4><%= @hello_message %></h4>
        </div>
      </row>

      <row>
        <div class="buttons">
            <%= link_to "New Post", new_post_path, class: 'button btn-primary btn-lg text-center' %>
            <%= link_to "Logout", "/sessions", class: 'button btn-info btn-lg text-center', method: :delete %>
        </div>
      </row>

      <row>
        <div class="posts">
          <% @posts.each do |post| %>
            <div class="post-container">
              <%= image_tag post.image.url, class: 'img-responsive' %>
              <div class="post-caption">
                <%= post.caption %>
              </div>
            </div>
          <% end %>
        </div>
      </row>

    </section>
  </body>
</html>

app/views/layouts/_flash_messages.html.erb
<div id="flash-messages-container">
  <% flash.each do |k,v| %>
    <section class="flash-messages">
      <div class="alert alert-<%=k%>">
        <button type="button" id="close-flash" class="close" data-dismiss="alert">
          &times;
        </button>
        <div class="message">
          <%= display_message(v) %>
        </div>
      </div>
    </section>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hipstergram</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/flash_messages" %>
    <%= yield %>
  </body>
</html>

app/views/password_resets/edit.html.erb
<div class="password-resets edit">
  <div class="content">
    <%= form_for(:user, url: password_reset_path(id: @token), method: :patch, html: { id: "user-set-new-password-form"}) do |f| %>
      <h1 class="white shadowed text-center">
        Set New Password
      </h1>

      <div class="form-group">
        <h4> <%= f.label :password_field, "Password", class: "" %> </h4>
        <%= f.password_field :password, required: true, id: 'user_password_field', class: 'form-control' %>
      </div>

      <div class="form-group text-center">
        <%= f.submit "Update my password!", class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<section class="password-resets new">
  <div class="content">
    <%= form_for(:reset, url: password_resets_path, method: :post) do |f| %>
      <h1 class="text-center">Reset My Password</h1>

      <div class="form-group">
        <h4><%=f.label :email_field, "Email", class: '' %></h4>
        <%= f.email_field :email, required: true, id: "user_email_field", class: "form-control" %>
      </div>

      <div class="form-group text-center">
        <%= f.submit "Reset my password", class: 'btn btn-primary btn-lg' %>
      </div>
    <% end %>

    <h5 class="text-center">
      <%= link_to "Return home", root_path, class: '' %>
    </h5>
  </div>
</section>        

app/views/posts/new.html.erb
<section class="posts new">
  <div class="content">
    <%= form_for(:post, url: posts_path, method: :post) do |f| %>
      <h1 class="text-center">Create new post</h1>

      <div class="form-group">
        <h4><%= f.label :image_field, "Picture", class: ''%></h4>
        <%= f.file_field :image, id: "post_image_field", class: "form-control" %>
      </div>

      <div class="form-group">
        <h4><%= f.label :caption, "Caption", class: '' %></h4>
        <%= f.text_field :caption, id: "post_caption_field", class: 'form-control' %>
      </div>

      <div class="form-group text-center">
        <%= f.submit "Create new post", class: 'btn btn-primary btn-lg' %>
      </div>
    <% end %>

    <h5 class= "text-center">
      <%= link_to "Return to dashboard", dashboard_index_path, class: '' %>
    </h5>    
  </div>
</section>

app/views/posts/show.html.erb
<html>
  <body>
    <section class="post">
      <div class="content">
        <%= link_to "Back", request.referer || dashboard_index_path %>
        <div class="image-container">
          <%= image_tag @post.image.url, class: 'img-responsive' %>
        </div>

        <div class="caption-container text-center">
          <h2><%= @post.caption %></h2>
        </div>
      </div>
    </section>
  </body>
</html>         

app/views/static_pages/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HIPSTERGRAM</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <section class="landing">
      <div class="main-content">
        <div class="main-title">
          <h1>HIPSTERGRAM</h1>
          <h3>It's time to take your creatives to the next level.</h3>
        </div>
        <br>
        <% if current_user %>
          <div class="buttons">
            <%= link_to "Dashboard", "/dashboard", class: 'button btn-success btn-lg text-center' %>
          </div>
        <% else %>
          <div class="buttons">
            <%= link_to "Sign Up", new_user_path, class: 'button btn-primary btn-lg text-center' %>
            <%= link_to "Log In", new_sessions_path, class: 'button btn-info btn-lg text-center' %>
          </div>
        <% end %>
      </div>
    </section>





  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE HTML>
<html>
  <head>
    <title>Sign Up Today!</title>
  </head>

  <body>
    <section class="users new">
      <div class="content">
        <%= form_for(:user, url: users_path, method: :post) do |f| %>
          <h1 class="text-center">Sign Up</h1>

          <div class="form-group">
            <h4><%= f.label :email_field, "Email", class: '' %></h4>
            <%= f.email_field :email, required: true, id: "user_email_field", class: "form-control" %>
          </div>

          <div class="form-group">
            <h4><%= f.label :username, "Username", class: '' %></h4>
            <%= f.text_field :username, required: true, id: "user_username_field", class: 'form-control' %>
          </div>

          <div class="form-group">
            <h4><%= f.label :password_field, "Password", class: '' %></h4>
            <%= f.password_field :password, required: true, id: "user_password_field", class: 'form-control'%>
          </div>

          <div class="form-group text-center">
            <%= f.submit "Sign me up!", class: 'btn btn-primary btn-lg' %>
          </div>
        <% end %>

        <h5 class="text-center">
          <%= link_to "I already have an account", new_sessions_path, class: '' %>
        </h5>

        <h5 class="text-center">
          <%= link_to "Return home", root_path, class: '' %>
        </h5>
      </div>
    </section>


  </body>


</html>